# Generated by Django 2.2 on 2020-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='address',
        ),
        migrations.AddField(
            model_name='coop',
            name='addresses',
            field=models.ManyToManyField(to='address.Address'),
        ),
        migrations.AlterField(
            model_name='cooptype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='cooptype',
            constraint=models.UniqueConstraint(fields=('name',), name='coop_type_unq'),
        ),
    ]
