# Generated by Django 3.2 on 2022-01-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('directory', '0005_coop_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CoopAddressTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_is_public', models.BooleanField(default=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.coop')),
            ],
        ),
        migrations.RemoveField(
            model_name='coop',
            name='addresses',
        ),
        migrations.AddField(
            model_name='coop',
            name='addresses',
            field=models.ManyToManyField(through='directory.CoopAddressTags', to='address.Address'),
        ),
    ]
