# Generated by Django 3.2 on 2021-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_coop_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coop',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
