# Generated by Django 3.2 on 2022-01-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_coop_approved'),
        ('directory', '0006_auto_20220120_1940'),
    ]

    operations = [
    ]
