# Generated by Django 3.2 on 2022-02-13 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_merge_20220130_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopChange',
            fields=[
                ('coop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directory.coop')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            bases=('directory.coop',),
        ),
    ]
