# Generated by Django 3.2 on 2022-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_coopchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='coop',
            name='proposed',
            field=models.JSONField(null=True, verbose_name='Proposed Changes'),
        ),
        migrations.DeleteModel(
            name='CoopChange',
        ),
    ]
