# Generated by Django 3.2 on 2022-03-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20220313_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopaddresstags',
            old_name='address_is_public',
            new_name='is_public',
        ),
    ]
