# Generated by Django 3.2 on 2022-04-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_rename_address_is_public_coopaddresstags_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coop',
            old_name='proposed',
            new_name='proposed_changes',
        ),
    ]
