# Generated by Django 3.2 on 2022-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_rename_proposed_coop_proposed_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coop',
            name='reject_reason',
            field=models.TextField(null=True),
        ),
    ]
