# Generated by Django 3.1.14 on 2022-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_coop_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='coops',
            field=models.ManyToManyField(to='directory.Coop'),
        ),
        migrations.RemoveField(
            model_name='coop',
            name='email',
        ),
        migrations.AddField(
            model_name='coop',
            name='email',
            field=models.ManyToManyField(null=True, related_name='contact_email', to='directory.ContactMethod'),
        ),
        migrations.RemoveField(
            model_name='coop',
            name='phone',
        ),
        migrations.AddField(
            model_name='coop',
            name='phone',
            field=models.ManyToManyField(null=True, related_name='contact_phone', to='directory.ContactMethod'),
        ),
    ]
