# Generated by Django 3.1.14 on 2022-12-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_coop_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coop',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coop', to='directory.coop'),
        ),
    ]
