# Generated by Django 3.1.14 on 2023-04-20 03:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0013_auto_20221219_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='email_is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='phone_is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='coop_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='rec_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='rec_updated_by',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coop',
            name='rec_updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coop',
            name='scope',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
