# Generated by Django 2.0 on 2020-04-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='type',
        ),
        migrations.AddField(
            model_name='coop',
            name='types',
            field=models.ManyToManyField(to='maps.CoopType'),
        ),
    ]
