FROM python:3.9
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/

RUN python -m pip install --upgrade pip
RUN apt-get update && apt-get -y install python3-dev

COPY pyproject.toml .

RUN python -m pip install --root-user-action ignore --upgrade pip uv
RUN uv sync

ENTRYPOINT ["./entrypoint_dev.sh"]
