FROM python:3.9
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/

RUN apt-get update \
    && apt-get install -y --no-install-recommends vim postgresql-client python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .

RUN python -m pip install --root-user-action ignore --upgrade pip uv
RUN uv sync

COPY . /code/

ENTRYPOINT ["./entrypoint_prod.sh"]
