[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.10.0",
    "astroid>=3.3.11",
    "attrs>=25.4.0",
    "backoff>=2.2.1",
    "cachetools>=6.2.0",
    "certifi>=2025.10.5",
    "charset-normalizer>=3.4.3",
    "django>=5.2.7",
    "django-address>=0.2.8",
    "django-cms>=5.0.4",
    "django-cors-headers>=4.9.0",
    "django-extensions>=4.1",
    "django-phonenumber-field>=8.3.0",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.28.0",
    "factory-boy>=3.3.3",
    "faker>=37.11.0",
    "geographiclib>=2.1",
    "geopy>=2.4.1",
    "google-auth>=2.41.1",
    "google-auth-oauthlib>=1.2.2",
    "gspread>=6.2.1",
    "gunicorn>=23.0.0",
    "idna>=3.10",
    "inflection>=0.5.1",
    "isort>=6.1.0",
    "jsonschema>=4.25.1",
    "jsonschema-specifications>=2025.9.1",
    "lazy-object-proxy>=1.12.0",
    "mccabe>=0.7.0",
    "more-itertools>=10.8.0",
    "numpy>=2.3.3",
    "oauthlib>=3.3.1",
    "packaging>=25.0",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "phonenumbers>=9.0.16",
    "pillow>=11.3.0",
    "pluggy>=1.6.0",
    "psycopg2-binary>=2.9.11",
    "py>=1.11.0",
    "pyasn1>=0.6.1",
    "pyasn1-modules>=0.4.2",
    "pycountry>=24.6.1",
    "pyjwt>=2.10.1",
    "pylint>=3.3.9",
    "pytest>=8.4.2",
    "python-dateutil>=2.9.0.post0",
    "pytz>=2025.2",
    "pyyaml>=6.0.3",
    "ratelimit>=2.2.1",
    "uwsgi>=2.0.30",
]
